version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: gateway_shareIt
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    container_name: server_shareIt
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareIt

  db:
    image: postgres:14
    container_name: db_shareIt
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=password